version: '3.8'
services:
  app:
    build: .
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - app-network
        
  file-server:
    build: ./file-server
    ports:
      - "8081:8081"
    restart: unless-stopped
    volumes:
      - ./file-server/uploads:/app/uploads
    networks:
      - app-network

networks:
  app-network:
    external: true