INSERT INTO positions (id, name) VALUES
('pediatrician', 'педиатр'),
('gynecologist_endocrinologist', 'гинеколог-эндокринолог'),
('ultrasound_doctor', 'врач УЗИ'),
('gynecologist', 'гинеколог'),
('mammologist', 'маммолог'),
('dermatologist', 'дерматолог'),
('venereologist', 'венеролог'),
('pediatric_dermatologist', 'детский дерматолог'),
('obstetrician', 'акушер'),
('physiotherapist', 'физиотерапевт'),
('cardiologist', 'кардиолог'),
('neurologist', 'невролог'),
('manual_therapist', 'мануальный терапевт'),
('therapist', 'терапевт'),
('endocrinologist', 'эндокринолог'),
('urologist', 'уролог'),
('andrologist', 'андролог'),
('sexologist', 'сексолог'),
('mycologist', 'миколог'),
('homeopath', 'гомеопат'),
('psychotherapist', 'психотерапевт'),
('rheumatologist', 'ревматолог'),
('functional_diagnostician', 'функциональный диагност'),
('oncologist_mammologist', 'онколог-маммолог'),
('surgeon', 'хирург')
ON CONFLICT (id) DO NOTHING;