INSERT INTO doctors (id, last_name, first_name, patronymic, positions, experience, departments, is_active, available_for_appointment) VALUES
('629306-vasileva', 'Васильева', 'Галина', 'Борисовна', '{"pediatrician"}', 44, '{"pediatrics"}', true, true),
('283136-leonteva', 'Леонтьева', 'Наталья', 'Владимировна', '{"gynecologist_endocrinologist", "ultrasound_doctor", "gynecologist", "mammologist"}', 25, '{"gynecology"}', true, true),
('301580-pashyan', 'Пашян', 'Левон', 'Карапетович', '{"dermatologist", "venereologist", "pediatric_dermatologist"}', 44, '{"dermatology"}', true, true),
('629305-bedova', 'Бедова', 'Анна', 'Игоревна', '{"obstetrician", "ultrasound_doctor", "gynecologist", "pediatric_ultrasound_doctor", "physiotherapist"}', 30, '{"gynecology"}', true, true),
('865548-prokopov', 'Прокопов', 'Владимир', 'Евгеньевич', '{"dermatologist", "venereologist", "pediatric_dermatologist"}', 29, '{"dermatology"}', true, true),
('648795-yuganson', 'Югансон', 'Александра', 'Георгиевна', '{"dermatologist", "pediatric_dermatologist"}', 17, '{"dermatology"}', true, true),
('629622-cherkashin', 'Черкашин', 'Сергей', 'Викторович', '{"cardiologist"}', 38, '{"cardiology"}', true, true),
('9124-chernyavskiy', 'Чернявский', 'Игорь', 'Анатольевич', '{"neurologist", "manual_therapist"}', 26, '{"neurology"}', true, true),
('984484-aksenova', 'Аксенова', 'Дарья', 'Ивановна', '{"therapist"}', 41, '{"therapy"}', true, true),
('648550-popova', 'Калуцкая (Попова)', 'Наталья', 'Николаевна', '{"ultrasound_doctor", "therapist"}', 13, '{"therapy"}', true, true),
('631288-snegirev', 'Снегирев', 'Юрий', 'Николаевич', '{"endocrinologist"}', 13, '{"endocrinology"}', true, true),
('674452-petrova', 'Петрова', 'Инна', 'Викторовна', '{"dermatologist", "venereologist"}', 31, '{"dermatology"}', true, true),
('998573-malyshin', 'Малышкин', 'Дмитрий', 'Игоревич', '{"urologist", "andrologist", "ultrasound_doctor", "sexologist"}', 22, '{"urology"}', true, true),
('648588-ragozina', 'Рагозина', 'Ольга', 'Викторовна', '{"pediatrician"}', 8, '{"pediatrics"}', true, true),
('460407-sherkevich', 'Шеркевич', 'Сергей', 'Михайлович', '{"dermatologist", "venereologist", "pediatric_dermatologist", "mycologist"}', 58, '{"dermatology"}', true, true),
('860871-magadova', 'Магадова', 'Елена', 'Аслановна', '{"neurologist"}', 22, '{"neurology"}', true, true),
('955260-bagaryan', 'Багарян', 'Людмила', 'Валерьевна', '{"gynecologist_endocrinologist", "gynecologist", "ultrasound_doctor"}', 15, '{"gynecology"}', true, true),
('1301702-alihodzhaeva', 'Алиходжаева', 'Зебо', 'Баходировна', '{"gynecologist"}', 28, '{"gynecology"}', true, true),
('497756-chubukov', 'Чубуков', 'Юрий', 'Афанасьевич', '{"ultrasound_doctor", "homeopath"}', 59, '{"therapy"}', true, true),
('714520-docenko', 'Доценко', 'Сергей', 'Николаевич', '{"psychotherapist"}', 20, '{"psychotherapy"}', true, true),
('941428-buzaev', 'Бузаев', 'Илья', 'Анатольевич', '{"psychotherapist"}', 31, '{"psychotherapy"}', true, true),
('634120-dergalina', 'Епифанова (Дергалина)', 'Наталья', 'Анатольевна', '{"rheumatologist", "therapist"}', 20, '{"therapy"}', true, true),
('8973-oflidi', 'Офлиди', 'Ирина', 'Владимировна', '{"gynecologist", "obstetrician"}', 29, '{"gynecology"}', true, true),
('167147-kokorin', 'Кокорин', 'Владимир', 'Викторович', '{"neurologist"}', 13, '{"neurology"}', true, true),
('8939-zabrovskaya', 'Забровская', 'Анна', 'Анатольевна', '{"gynecologist", "ultrasound_doctor", "gynecologist_endocrinologist"}', 19, '{"gynecology"}', true, true),
('597552-ponomar', 'Пономарь', 'Ольга', 'Вилорьевна', '{"pediatrician", "gastroenterologist", "infectious_disease_specialist", "therapist", "functional_diagnostician"}', 19, '{"pediatrics"}', true, true),
('797876-sheverdina', 'Шевердина', 'Наталья', 'Геннадьевна', '{"ultrasound_doctor", "pediatric_ultrasound_doctor", "mammologist", "oncologist_mammologist", "surgeon"}', 20, '{"therapy"}', true, true),
('534237-didenko', 'Диденко', 'Ирина', 'Дмитриевна', '{"therapist", "cardiologist"}', 46, '{"therapy"}', true, true),
('460410-dubrovina', 'Дубровина', 'Наталья', 'Владимировна', '{"therapist"}', 43, '{"therapy"}', true, true)
ON CONFLICT (id) DO NOTHING;